### ISSUE TITLE
Compile error for RealSense Sample\PointCloud 

### ISSUE THREAD

**Issue by chuacb** [UnaNancyOwen/RealSense2Sample#4]
Hi,

I am trying to compile the Point Cloud in Visual Studio 2015, during the compilation received an error saying that **"Cannot open include file: 'opencv2/viz.hpp': No such file or directory."**

Do I need to install the VTK inorder for this to work ?

Advice needed, thank you.

**Comment by UnaNancyOwen** [comment]
It is require Viz module of OpenCV. You need to build and install OpenCV from source code yourself, because it is not contain in pre-built package that distributed by official page of OpenCV. (By the way, Viz module dependent on VTK. If you not install VTK, You need install VTK before build OpenCV.)
I can't give step-by-step detailed advice about it. If you want more information, Please search by google.

**Comment by chuacb** [comment]
thank you ... i will make a try. appreciate the clue given. cheers
